{% set name = "xmlschema" %}
{% set version = "0.9.23" %}
{% set file_ext = "tar.gz" %}
{% set sha256 = "513043307b7fcb1fc52d89f6fc8325dbe2c5106cd43443e0a5b37466a12b1e6d" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.{{ file_ext }}
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ file_ext }}
  sha256: {{ sha256 }}

build:
  number: 0
  script: python setup.py install  --single-version-externally-managed --record=record.txt
  noarch: python

requirements:
  build:
    - python
    - setuptools
  run:
    - python

test:
  imports:
    - xmlschema
    - xmlschema.validators
    - xmlschema.tests

about:
  home: https://github.com/brunato/xmlschema
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: An XML Schema validator and decoder
  description: |
      An implementation of XML Schema <http://www.w3.org/2001/XMLSchema> for
      Python (supports versions 2.7 and Python 3.3+).

      The xmlschema library includes the following features: building of XML
      schema objects from XSD files; validation of XML instances with XSD
      schemas; decoding of XML data into Python data structures; an XPath based
      API for finding schema's elements and attributes; support of XSD
      validation modes.

  dev_url: https://github.com/brunato/xmlschema

extra:
  recipe-maintainers:
    - ccwang002
