{% set name = "xmlschema" %}
{% set version = "3.3.1" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 2066ecbc9728112073f6f44d17c5c16723aff1c7d22a7c4c6421e2d68ec5f0ea

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  noarch: python

requirements:
  host:
    - python >=3.8
    - pip
    - elementpath <5.0.0,>=4.4.0

  run:
    - python >=3.8
    - elementpath <5.0.0,>=4.4.0

test:
  requires:
    - jinja2
    - lxml
    - pip
  source_files:
    - tests
  imports:
    - xmlschema
  commands:
    - python tests/test_all.py
    - pip check

about:
  home: https://github.com/sissaschool/xmlschema
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: An XML Schema validator and decoder
  description: |
    This is an implementation of XML Schema for Python 3.8+.

    This library arises from the needs of a solid Python layer for processing
    XML Schema based files for MaX (Materials design at the Exascale) European
    project. A significant problem is the encoding and the decoding of the XML
    data files produced by different simulation software. Another important
    requirement is the XML data validation, in order to put the produced data
    under control. The lack of a suitable alternative for Python in the
    schema-based decoding of XML data has led to build this library. Obviously
    this library can be useful for other cases related to XML Schema based
    processing, not only for the original scope.

  dev_url: https://github.com/sissaschool/xmlschema

extra:
  recipe-maintainers:
    - ccwang002
