{% set name = "xmlschema" %}
{% set version = "1.0.6" %}
{% set file_ext = "tar.gz" %}
{% set sha256 = "59268d16cd691883b23f38b3ddf6548ee50e45029ccc619e6fcc0c5367016c36" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.{{ file_ext }}
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ file_ext }}
  sha256: {{ sha256 }}

build:
  number: 0
  script: python -m pip install --no-deps --ignore-installed .
  noarch: python

requirements:
  build:
    - python
    - pip
    - elementpath>=1.0.6
    - defusedxml>=0.5

  run:
    - python
    - elementpath>=1.0.6
    - defusedxml>=0.5

test:
  imports:
    - xmlschema
    - xmlschema.validators
    - xmlschema.tests

about:
  home: https://github.com/brunato/xmlschema
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: An XML Schema validator and decoder
  description: |
    This is an implementation of XML Schema for Python (supports versions 2.7
    and Python 3.3+).

    This library arises from the needs of a solid Python layer for processing
    XML Schema based files for MaX (Materials design at the Exascale) European
    project. A significant problem is the encoding and the decoding of the XML
    data files produced by different simulation software. Another important
    requirement is the XML data validation, in order to put the produced data
    under control. The lack of a suitable alternative for Python in the
    schema-based decoding of XML data has led to build this library. Obviously
    this library can be useful for other cases related to XML Schema based
    processing, not only for the original scope.

  dev_url: https://github.com/brunato/xmlschema

extra:
  recipe-maintainers:
    - ccwang002
